"""
This script will have methods/Threads that help create data for different other threads
1. offline_lstm_data_gen:
	Whenever lstm_train_data_lock is free, do in a never-ending loop
	a. read the stored file and create lstm related data for the last 3 months + 1 week
	b. read the stored file and create environment related data for last 3 months + 1 week over same period
	* This method needs to know a timestamp as an input based on which it will get data from offline database.
2. online_data_process : Use stats generated by data_stats to process data online
"""

# imports
import numpy as np


def offline_lstm_data_gen(*args, **kwargs):

	time_stamp = kwargs['time_stamp']
	